"""
backend/database/models.py
───────────────────────────
SQLAlchemy ORM models.

Tables
------
users                    — registered accounts
scan_results             — every persisted scan (linked to user or anonymous)
alerts                   — security alerts generated by rules/events
incidents                — SOC incident containers aggregating alerts
monitoring_targets       — continuous target monitoring registrations
notification_preferences — per-user channel & severity alert configuration
notifications            — in-app user notifications
audit_events             — system audit trail
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, backref, relationship


def _utcnow():
    return datetime.now(timezone.utc)


def _uuid_str():
    return str(uuid.uuid4())


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id            = Column(Integer, primary_key=True, index=True)
    email         = Column(String(255), unique=True, index=True, nullable=False)
    hashed_pw     = Column(String(255), nullable=False)
    role          = Column(String(50), default="user", nullable=False)
    is_active     = Column(Boolean, default=True, nullable=False)
    created_at    = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    scans         = relationship("ScanResult", back_populates="user", lazy="selectin")


class ScanResult(Base):
    __tablename__ = "scan_results"

    __table_args__ = (
        Index("idx_scan_results_user_created", "user_id", "created_at"),
    )

    id            = Column(Integer, primary_key=True, index=True)
    url           = Column(Text, nullable=False)
    prediction    = Column(String(64), nullable=False)
    confidence    = Column(Float, nullable=False)
    latency_ms    = Column(Float, nullable=True)
    cache_hit     = Column(Boolean, default=False, nullable=False)

    # SHAP top-reasons stored as JSON; populated by background task
    top_reasons   = Column(JSON, nullable=True)

    # ── Sprint 2: Zero-Day Ingestion Fields ───────────────────────────────────
    is_zero_day   = Column(Boolean, default=False, nullable=False)
    feature_vector = Column(JSON, nullable=True)
    source_feed   = Column(String(64), nullable=True)

    # ── Sprint 3: Active Learning & Retraining Tracking ──────────────────────
    is_retrained     = Column(Boolean, default=False, nullable=False, index=True)
    verified_label   = Column(String(64), nullable=True)
    label_provenance = Column(String(128), nullable=True)
    retrain_status   = Column(String(32), default="UNVERIFIED", nullable=False, index=True)
    retrain_attempt_count = Column(Integer, default=0, nullable=False)
    last_retrain_attempt  = Column(DateTime(timezone=True), nullable=True)
    retrained_at     = Column(DateTime(timezone=True), nullable=True)

    # ── Sprint 4: Threat Intelligence Enrichment Fields ──────────────────────
    domain_age_days       = Column(Integer, nullable=True)
    tls_valid             = Column(Boolean, nullable=True)
    redirect_count        = Column(Integer, nullable=True)
    final_url             = Column(Text, nullable=True)
    threat_intel_enrichment = Column(JSON, nullable=True)

    user_id       = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at    = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    user          = relationship("User", back_populates="scans")


# ── Sprint 5: SOC, Incident & Monitoring Models ───────────────────────────────

class Alert(Base):
    __tablename__ = "alerts"

    __table_args__ = (
        Index("idx_alerts_status_severity", "status", "severity"),
        Index("idx_alerts_indicator", "indicator_type", "indicator_value"),
    )

    id               = Column(Integer, primary_key=True, index=True)
    alert_uuid       = Column(String(36), default=_uuid_str, unique=True, index=True, nullable=False)
    title            = Column(String(255), nullable=False)
    description      = Column(Text, nullable=True)
    severity         = Column(String(32), default="MEDIUM", nullable=False, index=True)
    status           = Column(String(32), default="OPEN", nullable=False, index=True)
    rule_name        = Column(String(128), nullable=False)
    indicator_type   = Column(String(32), nullable=False)
    indicator_value  = Column(String(512), nullable=False, index=True)
    fingerprint      = Column(String(64), nullable=True, index=True)
    occurrence_count = Column(Integer, default=1, nullable=False)
    first_seen_at    = Column(DateTime(timezone=True), default=_utcnow, nullable=False)
    last_seen_at     = Column(DateTime(timezone=True), default=_utcnow, nullable=False)
    acknowledged_at  = Column(DateTime(timezone=True), nullable=True)
    resolved_at      = Column(DateTime(timezone=True), nullable=True)

    user_id          = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    incident_id      = Column(Integer, ForeignKey("incidents.id", ondelete="SET NULL"), nullable=True, index=True)

    user             = relationship("User", backref="alerts")
    incident         = relationship("Incident", back_populates="alerts")


class Incident(Base):
    __tablename__ = "incidents"

    __table_args__ = (
        Index("idx_incidents_status_severity", "status", "severity"),
    )

    id                  = Column(Integer, primary_key=True, index=True)
    incident_uuid       = Column(String(36), default=_uuid_str, unique=True, index=True, nullable=False)
    title               = Column(String(255), nullable=False)
    description         = Column(Text, nullable=True)
    severity            = Column(String(32), default="HIGH", nullable=False, index=True)
    status              = Column(String(32), default="OPEN", nullable=False, index=True)
    assigned_to_user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    created_by_user_id  = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    created_at          = Column(DateTime(timezone=True), default=_utcnow, nullable=False)
    updated_at          = Column(DateTime(timezone=True), default=_utcnow, nullable=False)
    closed_at           = Column(DateTime(timezone=True), nullable=True)
    resolution_notes    = Column(Text, nullable=True)

    alerts              = relationship("Alert", back_populates="incident", lazy="selectin")
    assigned_user       = relationship("User", foreign_keys=[assigned_to_user_id])
    creator_user        = relationship("User", foreign_keys=[created_by_user_id])


class MonitoringTarget(Base):
    __tablename__ = "monitoring_targets"

    __table_args__ = (
        Index("idx_mon_targets_next_check", "is_active", "next_check_at"),
    )

    id                     = Column(Integer, primary_key=True, index=True)
    target_uuid            = Column(String(36), default=_uuid_str, unique=True, index=True, nullable=False)
    url                    = Column(Text, nullable=False)
    normalized_domain      = Column(String(255), nullable=False, index=True)
    check_interval_minutes = Column(Integer, default=60, nullable=False)
    is_active              = Column(Boolean, default=True, nullable=False, index=True)
    last_checked_at         = Column(DateTime(timezone=True), nullable=True)
    next_check_at          = Column(DateTime(timezone=True), default=_utcnow, nullable=False, index=True)
    last_prediction        = Column(String(64), nullable=True)
    last_confidence        = Column(Float, nullable=True)
    consecutive_failures   = Column(Integer, default=0, nullable=False)

    user_id                = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    created_at             = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    user                   = relationship("User", backref="monitoring_targets")


class NotificationPreference(Base):
    __tablename__ = "notification_preferences"

    id              = Column(Integer, primary_key=True, index=True)
    user_id         = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True)
    in_app_enabled  = Column(Boolean, default=True, nullable=False)
    email_enabled   = Column(Boolean, default=False, nullable=False)
    webhook_enabled = Column(Boolean, default=False, nullable=False)
    webhook_url     = Column(Text, nullable=True)
    webhook_secret  = Column(String(255), nullable=True)
    min_severity    = Column(String(32), default="HIGH", nullable=False)
    updated_at      = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    user            = relationship("User", backref=backref("notification_preferences", uselist=False))


class Notification(Base):
    __tablename__ = "notifications"

    __table_args__ = (
        Index("idx_notifications_user_read", "user_id", "is_read"),
    )

    id                = Column(Integer, primary_key=True, index=True)
    notification_uuid = Column(String(36), default=_uuid_str, unique=True, index=True, nullable=False)
    user_id           = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title             = Column(String(255), nullable=False)
    message           = Column(Text, nullable=False)
    severity          = Column(String(32), default="INFO", nullable=False)
    is_read           = Column(Boolean, default=False, nullable=False, index=True)
    link_url          = Column(String(512), nullable=True)
    created_at        = Column(DateTime(timezone=True), default=_utcnow, nullable=False)

    user              = relationship("User", backref="notifications")


class AuditEvent(Base):
    __tablename__ = "audit_events"

    id              = Column(Integer, primary_key=True, index=True)
    event_uuid      = Column(String(36), default=_uuid_str, unique=True, index=True, nullable=False)
    action          = Column(String(128), nullable=False, index=True)
    actor_user_id   = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    target_resource = Column(String(128), nullable=False)
    resource_id     = Column(String(128), nullable=False)
    details         = Column(JSON, nullable=True)
    ip_address      = Column(String(45), nullable=True)
    created_at      = Column(DateTime(timezone=True), default=_utcnow, nullable=False, index=True)

    actor_user      = relationship("User", foreign_keys=[actor_user_id])
